if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'ayu-theme/ayu-vim'
Plug 'liuchengxu/space-vim-dark'
Plug 'Yggdroot/indentLine'
Plug 'scrooloose/nerdtree'
Plug 'elzr/vim-json'

call plug#end()

"autocmd vimenter * NERDTree starts nerdtree on vim startup.
map <C-n> :NERDTreeToggle<CR>
map <C-m> :NERDTreeFocus<CR>

set tabstop=2       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.
set shiftwidth=2    " Indents will have a width of 4
set softtabstop=2   " Sets the number of columns for a TAB
set expandtab       " Expand TABs to spaces

let g:vim_json_syntax_concealcursor = ""
let g:indentLine_concealcursor = ""

set directory^=$HOME/.vim/tmp// " send swap files on .vim folder

set number
set termguicolors     " enable true colors support

"let ayucolor="light"   " for dark version of theme

syntax on
colorscheme space-vim-dark 

hi Comment guifg=#5C6370 ctermfg=59

